[build]
    command = "npm run build && npm run postbuild"
    publish = "out"

[[redirects]]
  from = "https://drinksundthings.at"
  to = "https://drinksundthings.wien"
  status = 301
  force = false
  query = *

[[plugins]]
    package = "@netlify/plugin-nextjs"
[[plugins]]
    package = "netlify-plugin-cache-nextjs"
# [[plugins]]
#     package = "@netlify/plugin-sitemap"
#         [plugins.inputs]
#         baseUrl = "drinksandthings.wien"
#         changeFreq = "monthly"
#         buildDir = "out"
